Modified job submission scripts for ant

diff --git a/scripts/GoATFarm b/scripts/GoATFarm
--- a/scripts/GoATFarm
+++ b/scripts/GoATFarm
@@ -1,8 +1,9 @@
 #!/bin/sh
 #Give the args some sensible names
-ConfigFile=$1
-ServerFile=$2
-JobName=$3
+Executable=$1
+ConfigFile=$2
+ServerFile=$3
+JobName=$4
 
 
 ####################################################
@@ -10,7 +11,7 @@ JobName=$3
 ####################################################
 
 #Who'll get the emails from the farm
-MailAddress="$USER@kph.uni-mainz.de"
+MailAddress="wagners@kph.uni-mainz.de"
 
 ####################################################
 ###### End of section requiring editing ############
@@ -28,18 +29,19 @@ WALLTIME=24:00:00
 print_usage(){
     echo
     echo "Usage:"
-    echo "$exe <GoATConfig> <GoATServer> <JobName>"
+    echo "$exe <Executable> <GoATConfig> <GoATServer> <JobName>"
     echo
+    echo "<Executable>:   GoAT/ant executable which should be used"
     echo "<GoATConfig>:   Top level GoAT config file"
     echo "<GoATServer>:   Top level GoAT server file"
     echo "<JobName>:       A directory jobs/<JobName> will be created"
     echo "                 if it doesn't exist and scripts put there"
     echo "Example: "
-    echo "$exe configfiles/GoAT-Compton.dat configfiles/GoAT-Server.dat myjob"
+    echo "$exe goat configfiles/GoAT-Physics.dat configfiles/GoAT-Server.dat myjob"
 }
 
 #check that we have all the args, otherwise print use
-if [ $# -lt 3 ]; then
+if [ $# -lt 4 ]; then
     print_usage;
     exit 0;
 fi
@@ -52,12 +54,23 @@ InputPre=`gawk '{if($1=="Input-Prefix:")print $2}' $ServerFile`
 OutputDir=`gawk '{if($1=="Output-Directory:")print $2}' $ServerFile`
 OutputPre=`gawk '{if($1=="Output-Prefix:")print $2}' $ServerFile`
 
+GoatExe=""
+if [ -f $Executable ]; then
+    GoatExe=$Executable
+elif [ -f "build/bin/$Executable" ]; then
+    GoatExe="build/bin/$Executable"
+else
+    echo "Couldn't find the specified executable $Executable"
+    echo "Please provide the correct name or path"
+    exit 1;
+fi
+
 MainDir=`pwd`
 
 if [ -z $InputDir ]; then InputDir=`pwd`; fi
-if [ -z $InputPre ]; then InputPre="Acqu"; fi
+if [ -z $InputPre ]; then InputPre="GoAT"; fi
 if [ -z $OutputDir ]; then OutputDir=`pwd`; fi
-if [ -z $OutputPre ]; then OutputPre="GoAT"; fi
+if [ -z $OutputPre ]; then OutputPre="Analysis"; fi
 
 #make some subdirectories for job and setup files
 JobDir="jobs/$JobName"
@@ -82,7 +95,8 @@ while read line
 do
 
     echo "Making a job for File: $line";
-        
+    number=`echo $line | sed -r 's/.*_([0-9]*)\..*/\1/g'`
+
     #strip off the .root, and any directory paths
     BaseName=`basename $line .root | sed "s/${InputPre}/${OutputPre}/"`
     JobFile="${JobDir}/jobfiles/${BaseName}.sub"
@@ -93,7 +107,7 @@ do
 
     #now make the job file
     echo "#!/bin/sh" > $JobFile;
-    echo "#PBS -N GoAT_${USER}" >> $JobFile;
+    echo "#PBS -N GoAT_${USER}_$number" >> $JobFile;
     echo "#PBS -m abe" >> $JobFile;
     echo "#PBS -M $MailAddress"  >> $JobFile;
     echo "#PBS -V"  >> $JobFile;
@@ -104,6 +118,7 @@ do
     echo "#"  >> $JobFile;
     echo "#InputFiles: $line"   >> $JobFile;
     echo "#"  >> $JobFile;
+    echo "export GoAT_EXECUTABLE=\"$MainDir/$GoatExe\"" >> $JobFile;
     echo "export GoAT_MAINDIR=\"$MainDir\""  >> $JobFile;
     echo "export GoAT_CONFIGFILE=\"$ConfigFile\""  >> $JobFile;
     echo "export GoAT_INPUTFILE=\"$InputFile\""  >> $JobFile;
@@ -111,7 +126,7 @@ do
     echo "export GoAT_OUTPUTDIR=\"$OutputDir\""  >> $JobFile;
     echo "#"  >> $JobFile;
     echo "#This is the executable that gets run on the node"  >> $JobFile;
-    echo "GoATNode"  >> $JobFile;
+    echo "/home/wagners/a2/a2GoAT/scripts/GoATNode"  >> $JobFile;
     echo "#"  >> $JobFile;
     echo "exit 0"  >> $JobFile;
     echo "##end of job script"  >> $JobFile;
